# Generated by Django 5.1.2 on 2024-11-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"permissions": [("view_price", "Can view product price")]},
        ),
        migrations.AddField(
            model_name="product",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
