# Generated by Django 5.1.2 on 2024-12-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_product_options_product_is_public"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_public",
        ),
    ]
